### ISSUE TITLE
How to setup build env and build ?

### ISSUE THREAD

**Issue by TiNredmc** [jekhor/chromiumos_touch_keyboard#2]
I'm really new to the project "build" on linux. especially with GN and ninja. can you help me build this ?

**Comment by jekhor** [comment]
Now this project uses CMake. To build, do:
```
apt-get install cmake android-libbase-dev
mkdir build
cd build
cmake ..
make
```

Or just run dpkg-buildpackage -b -uc -us

**Comment by TiNredmc** [comment]
Oh, Thanks. First time I tried to buildbI was using ninja build (according to the buid file type I've found in the repo).
