### ISSUE TITLE
Chromium Port

### ISSUE THREAD

**Issue by nolanchromium** [jekhor/chromiumos_touch_keyboard#3]
Could you attach (as zip) to this issue the 3 below files taken from a chromiumos distro which supports your keyboard (most recent chromiumos release possible) ?

/usr/bin/touch_keyboard_handler
/opt/google/touch/policies/touch_keyboard_handler.policy
/etc/init/touch_keyboard.conf

**Comment by TiNredmc** [comment]
Hello, About the "touch_keyboard_handler", It's here [https://github.com/jekhor/yogabook-livecd/blob/297f8d2f509d7a48a07e41274fe835f7e702785c/config/includes.chroot/usr/sbin/touch_keyboard_handler](url). I also want to know about how to setup the building env. but he don't respond...

**Comment by jekhor** [comment]
> Hello, About the "touch_keyboard_handler", It's here [https://github.com/jekhor/yogabook-livecd/blob/297f8d2f509d7a48a07e41274fe835f7e702785c/config/includes.chroot/usr/sbin/touch_keyboard_handler](url). I also want to know about how to setup the building env. but he don't respond...

Sorry, I have seen this comments today only :(  I posted answer there.

**Comment by jekhor** [comment]
> Could you attach (as zip) to this issue the 3 below files taken from a chromiumos distro which supports your keyboard (most recent chromiumos release possible) ?
> 
> /usr/bin/touch_keyboard_handler
> /opt/google/touch/policies/touch_keyboard_handler.policy
> /etc/init/touch_keyboard.conf

There is no ChromiumOS for this device unfortunately exists.
